blog_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blogs.urls')),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', include('dashboards.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('<int:category_id>/', views.blogs_by_category, name='blogs_by_category'),
    path('<slug:slug>/', views.single_blog, name='single_blog'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category_name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)
    
    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.category_name
    
STATUS_CHOICES = (
    ('Draft', 'Draft'),
    ('Published', 'Published'),
)

class Blog(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150, unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d')
    short_description = models.TextField(max_length=500)
    blog_body = models.TextField(max_length=5000)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Draft')
    is_featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

class Comment(models.Model):
    comment = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Blogs</title>
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">

    <!-- CSS for Form size -->
    <style>
      @media (max-width: 767px) {
          /* Styles for small screens */
          form {
              width: auto; /* or any other style for small screens */
          }
      }
  
      @media (min-width: 768px) {
          /* Styles for medium and larger screens */
          form {
              width: 500px; /* Your specified width for medium and larger screens */
          }
      }
  </style>

  </head>
<body>
  
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="blog-header-logo text-dark" href="/">Django Blog</a>
          </div>
          <div class="col-4 pt-1">
            <form action="{% url 'search' %}" method="GET">
              <div class="input-group">
                <input class="form-control" type="text" name="keyword" value="{{keyword}}" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                <button type="submit" class="btn btn-warning" id="button-search" type="button">Go!</button>
            </div>
            </form>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            {% if not user.is_authenticated %}
            <a class="btn btn-sm btn-warning" href="{% url 'login' %}">Login</a> &nbsp;
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'register' %}">Register</a>
            {% else %}
            {% if perms.blogs.change_blog %}
            <a href="{% url 'dashboard' %}" class="btn btn-warning">Dashboard</a> 
            &emsp;
            {% endif %}
            <a href="{% url 'logout' %}" class="btn btn-warning">Logout</a>
            {% endif %}
          </div>
        </div>
      </header>

      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex justify-content-between">
          {% for category in categories %}
          <a class="p-2 text-muted" href="{%url 'blogs_by_category' category.id%}">{{category.category_name}}</a>
          {% endfor %}
        </nav>
      </div>

{% block content %}

{% endblock %}
<br><br>
<footer class="blog-footer">
  <p>Django blog built  by <a href="#">Yogesh Bhagat</a></p>
</footer>
</body>
</html>

templates/blogs_by_category.html
{% extends 'base.html' %}

{% block content %}
<!-- Recent Blogs -->

{% if blogs %}
  <h3 class="text-uppercase text-warning" style="letter-spacing: 2px;">Category - {{category}}</h3>
    <div class="row mb-2">
      {% for blog in blogs %}
        <div class="col-md-6">
          <div class="card border-0" >
            <div class="card-body">
              <h3>{{blog.title}}</h3>
              <small class="mb-1 text-muted">{{blog.created_at | timesince}} ago | {{blog.author}}</small>
              <p class="card-text">{{blog.short_description | truncatewords:25}}</p>
            </div>
          </div>
        </div>
      {% endfor %}
{% else %}
  <h3 class="text-uppercase text-warning" style="letter-spacing: 2px;" >No blogs found.</h3>
{% endif %}
  </div><!-- /.blog-main -->

    </div><!-- /.row -->

  </main><!-- /.container -->

</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% for featured_blog in featured_blogs %}
  {% if forloop.first %}
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark" style="background-image: url( {{featured_blog.image.url}} );background-blend-mode: overlay;background-size:cover;">
      <div class="col-md-8 px-0">
        <h1 class="display-4 font-italic">{{featured_blog.title}}</h1>
        <p class="lead my-3">{{featured_blog.short_description | truncatewords:25}}</p>
        <p class="lead mb-0"><a href="{% url 'single_blog' featured_blog.slug %}" class="text-white font-weight-bold">Continue reading...</a></p>
      </div>
  </div>
  {% endif %}
{% endfor %}

<!-- Featured Blogs -->
<h3 class="text-uppercase text-warning" style="letter-spacing: 2px;" >Featured Blogs</h3>
  <div class="row mb-2">
    {% for featured_blog in featured_blogs %}
    {% if not forloop.first %}
      <div class="col-md-6">
        <div class="card border-0" >
          <div class="card-body">
            <h3> <a href="{% url 'single_blog' featured_blog.slug %}" class="text-dark">{{featured_blog.title}}</a> </h3>
            <small class="mb-1 text-muted">{{featured_blog.created_at | timesince}} ago | {{featured_blog.author}}</small>
            <p class="card-text">{{featured_blog.short_description | truncatewords:25}}</p>
          </div>
        </div>
      </div>
    {% endif %}
    {% endfor %}
  </div>

<!-- Recent Blogs -->
<h3 class="text-uppercase text-warning" style="letter-spacing: 2px;" >Recent Blogs</h3>
  <main role="main" class="container p-0">
    <div class="row">
      <div class="col-md-8 blog-main">
        {% for recent_blog in recent_blogs %}
          <div class="card border-0" >
            <div class="card-body">
              <h3> <a href="{% url 'single_blog' recent_blog.slug %}" class="text-dark">{{recent_blog.title}}</a></h3>
              <small class="mb-1 text-muted">{{recent_blog.created_at | timesince}} ago | {{recent_blog.author}}</small>
              <p class="card-text">{{recent_blog.short_description | truncatewords:25}}</p>
            </div>
          </div>
        {% endfor %}
      </div>
      <!-- /.blog-main -->
    
      <aside class="col-md-4 blog-sidebar">
      {% for info in other_info %}
        <div class="p-3 mb-3 bg-light rounded">
          <h4 class="font-italic">{{ info.title }}</h4>
          <p class="mb-0"> {{ info.description }} </p>
        </div>
      {% endfor %}
      
      {% if social_links %}
        <div class="p-3">
          <h4 class="font-italic">Follow Us</h4>
          <ol class="list-unstyled">
          {% for social_link in social_links %}
            <li><a href="{{social_link.link}}" target="_blank">{{social_link.title}}</a></li>
          {% endfor %}
          </ol>
        </div>
      {% endif %}
      </aside><!-- /.blog-sidebar -->

    </div><!-- /.row -->

  </main><!-- /.container -->

</div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<form action="{% url 'login' %}" method="POST" style="margin: auto;">
  {% csrf_token %}
  {{ form |crispy }}
  <button type="submit" class="btn btn-warning" >Submit</button>
</form>
&emsp;

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<form action="{% url 'register' %}" method="POST" style="margin: auto;">
  {% csrf_token %}
  {{ form |crispy }}
  <button type="submit" class="btn btn-warning" >Submit</button>
</form>
&emsp;

{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block content %}

{% if blogs %}
  <h3 class="text-warning" style="letter-spacing: 2px;">Searched for - "{{keyword}}"</h3>
    <div class="row mb-2">
      {% for blog in blogs %}
        <div class="col-md-6">
          <div class="card border-0" >
            <div class="card-body">
              <h3> <a href="{% url 'single_blog' blog.slug %}" class="text-dark">{{blog.title}}</a></h3>
              <small class="mb-1 text-muted">{{blog.created_at | timesince}} ago | {{blog.author}}</small>
              <p class="card-text">{{blog.short_description | truncatewords:25}}</p>
            </div>
          </div>
        </div>
      {% endfor %}
{% else %}
  <h3 class="text-uppercase text-warning" style="letter-spacing: 2px;" >No results found.</h3>
{% endif %}

</div>

{% endblock %}

templates/single_blog.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Post header-->
                <header class="mb-4">
                    <!-- Post title-->
                    <h1 class="fw-bolder mb-1">{{blog.title}}</h1>
                    <!-- Post meta content-->
                    <div class="text-muted fst-italic mb-2">Posted on {{blog.created_at}} by {{blog.author.username}}</div>
                    <!-- Post category-->
                    <a class="badge bg-warning text-decoration-none text-light" href="{% url 'blogs_by_category' blog.category.id %}">{{blog.category}}</a>
                </header>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{blog.image.url}}" alt="..." /></figure>
                <!-- Post content-->
                <section class="mb-5">
                    <p class="fs-5 mb-4">{{blog.short_description}}</p>
                    <p class="fs-5 mb-4">{{blog.blog_body | linebreaks}}</p>
                </section>
                <!-- Comment -->
                <h3>Comments ({{comment_count}})</h3>
                {% if comments %}
                {% for comment in comments %}
                <div class="card mt-1">
                    <div class="card-body">
                        <span class="card-text">
                            {{comment}}
                            <div>
                                <small>By {{comment.user}} |</small>
                                <small>{{comment.created_at | timesince}} ago</small>
                            </div>
                        </span>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <span>No comments yet</span>
                {% endif %}
                <br>
                {% if user.is_authenticated %}
                <div class="form-group">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <textarea name="comment" class="form-control" placeholder="Write your comment here"></textarea>
                            <input type="submit" value="Submit" class="btn btn-primary mt-2">
                        </div>
                    </form>
                </div>
                {% else %}
                <p>Please <span><a href="{% url 'login' %}">Login</a></span> to write a comment</p>
                {% endif %}
            </article>
        </div>
        <!-- Side widgets-->
        <div class="col-lg-4">
            <!-- Search widget-->
            <div class="card mb-4">
            <!-- Categories widget-->

            {% if categories %}
            <div class="card mb-4 p-3">
                <h4 class="font-italic">Categories</h4>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="list-unstyled mb-0">
                                {% for category in categories %}
                                <li><a href="{% url 'blogs_by_category' category.id %}">{{category.category_name}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            <!-- Side widget-->
            {% if social_links %}
            <div class="card mb-4 p-3">
                <h4 class="font-italic">Follow Us</h4>
                {% for social_link in social_links %}
                <ol class="list-unstyled">
                    <li><a href="{{social_link.link}}" target="_blank">{{social_link.title}}</a></li>
                </ol>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}